import 'package:google_mlkit_translation/google_mlkit_translation.dart';

final Map<String, TranslateLanguage> languageMap = {
  "English": TranslateLanguage.english,
  "French": TranslateLanguage.french,
  "Spanish": TranslateLanguage.spanish,
  "German": TranslateLanguage.german,
  "Hindi": TranslateLanguage.hindi,
  "Chinese": TranslateLanguage.chinese,
  "Japanese": TranslateLanguage.japanese,
  "Korean": TranslateLanguage.korean,
  "Portuguese": TranslateLanguage.portuguese,
  "Italian": TranslateLanguage.italian,
  "Russian": TranslateLanguage.russian,
  "Arabic": TranslateLanguage.arabic,
  "Dutch": TranslateLanguage.dutch,
  "Turkish": TranslateLanguage.turkish,
  "Swedish": TranslateLanguage.swedish,
  "Greek": TranslateLanguage.greek,
  "Thai": TranslateLanguage.thai,
  "Hebrew": TranslateLanguage.hebrew,
  "Vietnamese": TranslateLanguage.vietnamese,
  "Bengali": TranslateLanguage.bengali,
  "Urdu": TranslateLanguage.urdu,
};

final Map<String, String> languageFlags = {
  "English": "🇬🇧",
  "French": "🇫🇷",
  "Spanish": "🇪🇸",
  "German": "🇩🇪",
  "Hindi": "🇮🇳",
  "Chinese": "🇨🇳",
  "Japanese": "🇯🇵",
  "Korean": "🇰🇷",
  "Portuguese": "🇵🇹",
  "Italian": "🇮🇹",
  "Russian": "🇷🇺",
  "Arabic": "🇸🇦",
  "Dutch": "🇳🇱",
  "Turkish": "🇹🇷",
  "Swedish": "🇸🇪",
  "Greek": "🇬🇷",
  "Thai": "🇹🇭",
  "Hebrew": "🇮🇱",
  "Vietnamese": "🇻🇳",
  "Bengali": "🇧🇩",
  "Urdu": "🇵🇰",
};
